# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The type of the application to build.
type: php:8.1
build:
  flavor: composer

dependencies:
  php:
    composer/composer: "^2"

# .platform.app.yaml
runtime:
  extensions:
    - gmp

# The hooks that will be performed when the package is deployed.
hooks:
  build: |
    set -e

  deploy: |
    rm -f bootstrap/cache/config.php
    rm -f bootstrap/cache/packages.php
    rm -f bootstrap/cache/routes-v7.php
    rm -f bootstrap/cache/services.php
    composer dumpautoload
    set -e
    php artisan optimize:clear
    php artisan optimize
    php artisan route:cache
    php artisan config:cache
    php artisan migrate --force

# The relationships of the affffffpplication with services or other applications.
# The left-hand side is the name offfff the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
#
relationships:
  database: "mysqldb:mysql"
  redis: "redis:redis"
# The size of the persistent disk of the application (in MB).
disk: 5048

# The mounts that will be performed when the package is deployed.
mounts:
  "storage/app/public": "shared:files/public"
  "storage/framework/views": "shared:files/views"
  "storage/framework/sessions": "shared:files/sessions"
  "storage/framework/cache": "shared:files/cache"
  "storage/framework/": "shared:files/framework"
  "storage/logs": "shared:files/logs"
  "bootstrap/cache": "shared:files/bootstrap/cache"
  "/.config": "shared:files/config"
  "storage": "shared:files/storage"
  "cache": "shared:files/esi/cache"
  "logs": "shared:files/esi/logs"
  "public/cache": "shared:files/esi/cache"
  "public/logs": "shared:files/esi/logs"
# The configuration of app when it is exp   osed to the web.
web:
  locations:
    "/":
      root: "public"
      index:
        - index.php
      allow: true
      passthru: "/index.php"
workers:
  schedule-work7:
    size: S
    commands:
      start: |
        php artisan schedule:daemon
  horizon-work7:
    size: M
    disk: 2048
    commands:
      start: |
        php artisan horizon
